import 'package:movie_app/domain/entities/movie_details_entity.dart';

MovieDetailsEntity mockMovieDetailsEntity = MovieDetailsEntity(
  title: 'title',
  year: 'year',
  rated: 'rated',
  released: 'released',
  runtime: 'runtime',
  genre: 'genre',
  director: 'director',
  writer: 'writer',
  actors: 'actors',
  plot: 'plot',
  language: 'language',
  country: 'country',
  awards: 'awards',
  poster: 'poster',
  ratings: [],
  metascore: 'metascore',
  imdbRating: 'imdbRating',
  imdbVotes: 'imdbVotes',
  imdbID: 'imdbID',
  type: 'type',
  dvd: 'dvd',
  boxOffice: 'boxOffice',
  production: 'production',
  website: 'website',
  response: 'response',
);
